### ISSUE TITLE
Sensitive data hard code

### ISSUE THREAD

**Issue by 0xthierry** [LauraBeatris/codio#4]
Hi,

I saw in your code that has sensitive data like password hard code.

https://github.com/LauraBeatris/codio/blob/master/src/services/api.js

**Comment by LauraBeatris** [comment]
Hi @thierrysantos 
Thank you so much for sending this issue <3 

I didn't notice that since the authentication feature isn't 100% done yet
Obs: I'll change a lot of things in the app structure because it's still using class-based components and there's a lot of unused stuff. 

Fixed in 81a26c4b3d2919701be463b799e5fa8d6077f5cd
